import { createClient } from "@sanity/client";

const client = createClient({
  projectId: "cav3bi02",
  dataset: "production",
  apiVersion: "2024-01-01",
  token: "skL48XjYDduYKJJTzyGtNfepfKtB9vpsQMvJ8Mu5Ud8XfWVSjcEZmxah8s56EfhSxno7ls2RzytaCBs0JyEA5et65qfnCfqIr7ph98whhH12oPCGxOKplGSkZlw8afXSl8X8Mv0VQ4k9QPBPUUblJF7o22vJ1BG1ToUiuZq6rHN9Ddn5QYMU",
  useCdn: false,
});

let k = 0;
function h2(text) { return { _type: "block", _key: "k" + k++, style: "h2", children: [{ _type: "span", _key: "s" + k, text, marks: [] }], markDefs: [] }; }
function h3(text) { return { _type: "block", _key: "k" + k++, style: "h3", children: [{ _type: "span", _key: "s" + k, text, marks: [] }], markDefs: [] }; }
function p(text) { return { _type: "block", _key: "k" + k++, style: "normal", children: [{ _type: "span", _key: "s" + k, text, marks: [] }], markDefs: [] }; }
function li(items) { return items.map(t => ({ _type: "block", _key: "k" + k++, style: "normal", listItem: "bullet", level: 1, children: [{ _type: "span", _key: "s" + k, text: t, marks: [] }], markDefs: [] })); }

const pages = [
  {
    _id: "legal-mentions",
    title: "Mentions légales",
    slug: { _type: "slug", current: "mentions-legales" },
    body: [
      p("Dernière mise à jour : 28 mars 2026"),
      h2("1. Éditeur du site"),
      p("Le site isotradition.ch est édité par :"),
      ...li(["Iso Tradition SA", "Route de Suisse 7A", "1295 Mies, Vaud, Suisse", "Téléphone : 021 624 53 00", "Email : contact@isotradition.ch", "Numéro IDE : CHE-XXX.XXX.XXX", "Registre du commerce : Canton de Vaud"]),
      h2("2. Directeur de la publication"),
      p("Le directeur de la publication est le représentant légal de la société Iso Tradition SA."),
      h2("3. Hébergement"),
      p("Le site est hébergé par :"),
      ...li(["Vercel Inc.", "440 N Barranca Ave #4133", "Covina, CA 91723, États-Unis", "Site web : vercel.com"]),
      h2("4. Propriété intellectuelle"),
      p("L'ensemble du contenu du site isotradition.ch (textes, images, graphismes, logo, icônes, vidéos, sons, logiciels, bases de données, etc.) est protégé par le droit d'auteur suisse et international."),
      p("Toute reproduction, représentation, modification, publication, adaptation ou exploitation de tout ou partie des éléments du site, quel que soit le moyen ou le procédé utilisé, est interdite sans l'autorisation écrite préalable d'Iso Tradition SA."),
      p("Les marques, logos et signes distinctifs présentés sur le site sont la propriété exclusive d'Iso Tradition SA ou de ses partenaires. Toute utilisation non autorisée constitue une contrefaçon au sens du droit suisse."),
      h2("5. Crédits"),
      ...li(["Conception et développement du site : MouaDev", "Photographies : Iso Tradition SA et banques d'images sous licence."]),
      h2("6. Limitation de responsabilité"),
      p("Iso Tradition SA s'efforce d'assurer l'exactitude et la mise à jour des informations diffusées sur son site, dont elle se réserve le droit de modifier le contenu à tout moment et sans préavis."),
      p("Iso Tradition SA ne saurait être tenue responsable des erreurs, omissions, ou des résultats qui pourraient être obtenus par un mauvais usage de ces informations."),
      p("Les liens hypertextes mis en place vers d'autres sites ne sauraient engager la responsabilité d'Iso Tradition SA quant au contenu de ces sites."),
      h2("7. Droit applicable et juridiction"),
      p("Le présent site et ses mentions légales sont régis par le droit suisse. En cas de litige, les tribunaux du canton de Vaud seront seuls compétents."),
    ],
  },
  {
    _id: "legal-cgu",
    title: "Conditions générales d'utilisation",
    slug: { _type: "slug", current: "cgu" },
    body: [
      p("Dernière mise à jour : 28 mars 2026"),
      h2("1. Objet"),
      p("Les présentes Conditions Générales d'Utilisation (ci-après \"CGU\") ont pour objet de définir les modalités et conditions dans lesquelles les utilisateurs accèdent et utilisent le site isotradition.ch (ci-après \"le Site\"), édité par Iso Tradition SA."),
      p("L'accès et l'utilisation du Site impliquent l'acceptation pleine et entière des présentes CGU. Si vous n'acceptez pas ces conditions, veuillez ne pas utiliser le Site."),
      h2("2. Accès au site"),
      p("Le Site est accessible gratuitement à tout utilisateur disposant d'un accès à Internet. Iso Tradition SA met en œuvre tous les moyens raisonnables pour assurer un accès continu au Site, mais ne saurait garantir une disponibilité permanente."),
      p("Iso Tradition SA se réserve le droit de suspendre, modifier ou interrompre temporairement ou définitivement l'accès au Site, sans préavis ni indemnité, notamment pour des raisons de maintenance ou de mise à jour."),
      h2("3. Utilisation du site"),
      p("L'utilisateur s'engage à utiliser le Site de manière conforme aux lois et réglementations en vigueur en Suisse. Il s'interdit notamment de :"),
      ...li(["Utiliser le Site à des fins illicites, frauduleuses ou portant atteinte aux droits de tiers", "Tenter de porter atteinte au fonctionnement du Site (piratage, introduction de virus, etc.)", "Collecter des données personnelles d'autres utilisateurs sans leur consentement", "Reproduire, copier ou distribuer le contenu du Site sans autorisation préalable", "Utiliser des robots, scrapers ou tout autre moyen automatisé pour accéder au Site"]),
      h2("4. Propriété intellectuelle"),
      p("L'ensemble des éléments du Site (textes, images, vidéos, logos, graphismes, icônes, sons, logiciels, etc.) est protégé par les lois suisses et internationales relatives à la propriété intellectuelle."),
      p("Ces éléments restent la propriété exclusive d'Iso Tradition SA. Toute reproduction, représentation, modification ou exploitation de tout ou partie de ces éléments est strictement interdite sans autorisation écrite préalable."),
      h2("5. Formulaires et données"),
      p("Le Site peut proposer des formulaires de contact ou de demande de devis. Les informations transmises via ces formulaires sont traitées conformément à notre Politique de confidentialité."),
      p("L'utilisateur garantit l'exactitude et la véracité des informations fournies via les formulaires du Site."),
      h2("6. Liens hypertextes"),
      p("Le Site peut contenir des liens hypertextes vers des sites tiers. Iso Tradition SA n'exerce aucun contrôle sur le contenu de ces sites et décline toute responsabilité quant à leur contenu ou à leur politique de confidentialité."),
      h2("7. Limitation de responsabilité"),
      p("Iso Tradition SA s'efforce de fournir des informations précises et actualisées sur le Site, mais ne garantit ni l'exactitude, ni l'exhaustivité des informations mises à disposition."),
      h2("8. Modification des CGU"),
      p("Iso Tradition SA se réserve le droit de modifier les présentes CGU à tout moment. Les modifications entrent en vigueur dès leur publication sur le Site."),
      h2("9. Droit applicable et juridiction"),
      p("Les présentes CGU sont régies par le droit suisse. Tout litige relatif à l'interprétation ou à l'exécution des présentes sera soumis à la compétence exclusive des tribunaux du canton de Vaud, Suisse."),
      h2("10. Contact"),
      p("Iso Tradition SA / Route de Suisse 7A, 1295 Mies / Téléphone : 021 624 53 00 / Email : contact@isotradition.ch"),
    ],
  },
  {
    _id: "legal-cgv",
    title: "Conditions générales de vente",
    slug: { _type: "slug", current: "cgv" },
    body: [
      p("Dernière mise à jour : 28 mars 2026"),
      h2("1. Champ d'application"),
      p("Les présentes Conditions Générales de Vente (ci-après \"CGV\") s'appliquent à l'ensemble des prestations et produits commercialisés par Iso Tradition SA, sise Route de Suisse 7A, 1295 Mies, Suisse."),
      p("Toute commande passée auprès du Prestataire implique l'acceptation sans réserve des présentes CGV."),
      h2("2. Produits et prestations"),
      p("Le Prestataire propose la fourniture et l'installation de :"),
      ...li(["Fenêtres (bois, PVC, aluminium, mixtes)", "Baies coulissantes", "Portes d'entrée", "Volets roulants et battants", "Portes de garage", "Stores bannes", "Films solaires", "Carports et pergolas"]),
      h2("3. Devis et commande"),
      p("Tout projet débute par une visite technique gratuite et sans engagement, suivie de l'établissement d'un devis détaillé."),
      p("Le devis est valable 30 jours à compter de sa date d'émission. La commande est considérée comme ferme après signature du devis et versement de l'acompte prévu."),
      h2("4. Prix et modalités de paiement"),
      p("Les prix indiqués dans les devis sont en francs suisses (CHF), toutes taxes comprises (TTC)."),
      ...li(["30 % d'acompte à la signature du devis", "40 % à la livraison des matériaux sur chantier", "30 % à la réception des travaux (solde)"]),
      p("En cas de retard de paiement, un intérêt moratoire de 5 % l'an sera appliqué conformément à l'article 104 du Code des obligations suisse (CO)."),
      h2("5. Délais de livraison et d'installation"),
      p("Les délais sont communiqués à titre indicatif. Le Prestataire s'engage à mettre en œuvre tous les moyens raisonnables pour respecter les délais convenus."),
      h2("6. Réception des travaux"),
      p("À l'achèvement des travaux, une réception contradictoire est organisée. Le client vérifie la conformité des travaux réalisés avec le devis accepté."),
      p("L'absence de réserves lors de la réception vaut acceptation définitive des travaux."),
      h2("7. Garanties"),
      ...li(["Garantie fabricant sur les produits : 10 à 20 ans selon les produits", "Garantie sur la pose : 2 ans à compter de la réception", "Garantie décennale : conformément aux usages de la branche en Suisse"]),
      h2("8. Droit de rétractation"),
      p("Le client dispose d'un délai de réflexion de 7 jours pour les contrats conclus à domicile (article 40a CO). Ce droit de révocation doit être exercé par écrit."),
      h2("9. Responsabilité"),
      p("La responsabilité du Prestataire est limitée aux dommages directs et prévisibles résultant d'un manquement avéré à ses obligations contractuelles."),
      h2("10. Protection des données"),
      p("Les données personnelles collectées sont traitées conformément à notre Politique de confidentialité et à la nLPD."),
      h2("11. Droit applicable et juridiction"),
      p("Les présentes CGV sont soumises au droit suisse. Tribunaux compétents : canton de Vaud, Suisse."),
      h2("12. Contact"),
      p("Iso Tradition SA / Route de Suisse 7A, 1295 Mies / Téléphone : 021 624 53 00 / Email : contact@isotradition.ch"),
    ],
  },
  {
    _id: "legal-cg-entretien",
    title: "Conditions générales d'entretien",
    slug: { _type: "slug", current: "cg-entretien" },
    body: [
      p("Dernière mise à jour : 28 mars 2026"),
      h2("1. Objet"),
      p("Les présentes Conditions Générales d'Entretien (ci-après \"CGE\") régissent les contrats de maintenance et d'entretien proposés par Iso Tradition SA pour les produits installés par ses soins : fenêtres, portes, volets, baies coulissantes et autres menuiseries extérieures."),
      h2("2. Contrat d'entretien"),
      p("Le contrat d'entretien est conclu pour une durée initiale d'un (1) an, renouvelable tacitement par périodes successives d'un an, sauf résiliation avec un préavis de trois (3) mois."),
      h2("3. Prestations incluses"),
      ...li(["Une visite d'entretien annuelle avec inspection complète des menuiseries", "Vérification et réglage des mécanismes d'ouverture et de fermeture", "Lubrification des ferrures, charnières et serrures", "Contrôle de l'étanchéité des joints et remplacement si nécessaire", "Nettoyage des rails de coulissement et des systèmes de drainage", "Vérification du bon fonctionnement des volets roulants et motorisations", "Rapport d'intervention détaillé avec recommandations"]),
      h2("4. Prestations exclues"),
      ...li(["Remplacement de vitrage cassé ou endommagé", "Réparations dues à un acte de vandalisme ou cas de force majeure", "Dommages résultant d'une utilisation non conforme", "Remplacement de pièces d'usure au-delà de l'entretien normal", "Modifications ou transformations des installations existantes"]),
      p("Ces prestations peuvent être réalisées sur devis séparé."),
      h2("5. Obligations du client"),
      ...li(["Assurer un entretien courant entre les visites", "Signaler sans délai toute anomalie constatée", "Permettre l'accès aux installations lors des visites planifiées", "Ne pas effectuer de modifications sans accord préalable"]),
      h2("6. Planification des interventions"),
      p("Les visites sont planifiées en accord avec le client. Toute annulation tardive (moins de 48h) pourra donner lieu à la facturation des frais de déplacement."),
      h2("7. Interventions d'urgence"),
      p("Les clients titulaires d'un contrat d'entretien bénéficient d'un délai d'intervention prioritaire. Les interventions hors heures ouvrables pourront faire l'objet d'une majoration tarifaire."),
      h2("8. Tarifs et paiement"),
      p("Le tarif est fixé dans le contrat individuel, révisable annuellement avec notification préalable de 30 jours. Paiement à 30 jours."),
      h2("9. Responsabilité"),
      p("Le Prestataire s'engage à effectuer les prestations avec le soin requis. Sa responsabilité est limitée aux dommages directs résultant d'une faute avérée."),
      h2("10. Garantie complémentaire"),
      p("La souscription d'un contrat d'entretien régulier constitue une condition de maintien de certaines garanties fabricant étendues."),
      h2("11. Droit applicable et juridiction"),
      p("Les présentes CGE sont soumises au droit suisse. Tribunaux compétents : canton de Vaud, Suisse."),
      h2("12. Contact"),
      p("Iso Tradition SA / Route de Suisse 7A, 1295 Mies / Téléphone : 021 624 53 00 / Email : contact@isotradition.ch"),
    ],
  },
  {
    _id: "legal-confidentialite",
    title: "Politique de confidentialité & Cookies",
    slug: { _type: "slug", current: "confidentialite" },
    body: [
      p("Dernière mise à jour : 28 mars 2026"),
      h2("1. Introduction"),
      p("Iso Tradition SA, sise Route de Suisse 7A, 1295 Mies, Suisse, s'engage à protéger la vie privée des utilisateurs de son site isotradition.ch."),
      p("La présente politique décrit les données personnelles que nous collectons, les finalités de leur traitement, ainsi que vos droits, conformément à la nouvelle Loi fédérale sur la protection des données (nLPD)."),
      h2("2. Responsable du traitement"),
      p("Iso Tradition SA / Route de Suisse 7A / 1295 Mies, Vaud, Suisse / Téléphone : 021 624 53 00 / Email : contact@isotradition.ch"),
      h2("3. Données collectées"),
      ...li(["Données d'identification : nom, prénom, adresse postale, adresse email, numéro de téléphone", "Données relatives au projet : type de bien, nature des travaux souhaités", "Données de navigation : adresse IP, type de navigateur, pages visitées, durée de visite, cookies", "Données de communication : contenu des messages envoyés via le formulaire de contact"]),
      h2("4. Finalités du traitement"),
      ...li(["Répondre à vos demandes de contact et de devis", "Établir et exécuter des contrats de vente et d'entretien", "Planifier les visites techniques et les interventions", "Améliorer la qualité de nos services et de notre site web", "Envoyer des communications commerciales (avec votre consentement)", "Respecter nos obligations légales et réglementaires", "Analyser la fréquentation et l'utilisation du site"]),
      h2("5. Base juridique du traitement"),
      ...li(["L'exécution d'un contrat ou de mesures précontractuelles", "Votre consentement (formulaire de contact, newsletter, cookies non essentiels)", "Nos intérêts légitimes (amélioration du site, sécurité)", "Le respect d'obligations légales (facturation, archivage)"]),
      h2("6. Durée de conservation"),
      ...li(["Données de prospection : 2 ans après le dernier contact", "Données clients : durée de la relation contractuelle + 10 ans", "Données de navigation et cookies : 13 mois maximum", "Communications commerciales : jusqu'au retrait de votre consentement"]),
      h2("7. Partage des données"),
      p("Vos données peuvent être partagées avec nos sous-traitants, partenaires et prestataires techniques. Nous ne vendons ni ne louons vos données personnelles à des tiers."),
      h2("8. Cookies"),
      ...li(["Cookies essentiels : nécessaires au fonctionnement du site", "Cookies analytiques : mesure d'audience (Google Analytics ou équivalent)", "Cookies de préférences : mémorisation de vos choix"]),
      p("Vous pouvez gérer vos préférences de cookies à tout moment via le bandeau de consentement ou les paramètres de votre navigateur."),
      h2("9. Vos droits"),
      ...li(["Droit d'accès : obtenir confirmation et copie de vos données", "Droit de rectification : corriger des données inexactes", "Droit à l'effacement : demander la suppression de vos données", "Droit d'opposition : vous opposer au traitement", "Droit à la portabilité : recevoir vos données dans un format structuré", "Droit de retirer votre consentement : à tout moment"]),
      p("Pour exercer vos droits, contactez-nous à contact@isotradition.ch. Délai de réponse : 30 jours."),
      h2("10. Sécurité des données"),
      p("Nous mettons en œuvre des mesures techniques et organisationnelles appropriées : chiffrement SSL/TLS, contrôle des accès, sensibilisation du personnel."),
      h2("11. Modifications"),
      p("Nous nous réservons le droit de modifier la présente politique à tout moment. Toute modification sera publiée sur cette page."),
      h2("12. Contact"),
      p("Iso Tradition SA / Route de Suisse 7A, 1295 Mies / Téléphone : 021 624 53 00 / Email : contact@isotradition.ch"),
    ],
  },
];

for (const page of pages) {
  await client.createOrReplace({ _type: "legalPage", ...page });
  console.log(`✅ ${page.title}`);
}

console.log("\n🎉 All legal pages seeded!");
